name: tidepool-deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/936777741784/locations/global/workloadIdentityPools/tidepool-github/providers/github

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build
        env:
          DOCKER_BUILDKIT: "1"
        run: |
          docker pull us-central1-docker.pkg.dev/bitly-tidepool-dev/tidepool-managed/hello-world:latest || true
          docker build \
            --cache-from=us-central1-docker.pkg.dev/bitly-tidepool-dev/tidepool-managed/hello-world:latest \
            -t us-central1-docker.pkg.dev/bitly-tidepool-dev/tidepool-managed/hello-world:${{ github.sha }} \
            -t us-central1-docker.pkg.dev/bitly-tidepool-dev/tidepool-managed/hello-world:latest \
            .

      - name: Push
        run: docker push --all-tags us-central1-docker.pkg.dev/bitly-tidepool-dev/tidepool-managed/hello-world

      - name: Deploy
        run: |
          gcloud run services update tidepool-hello-world \
            --image=us-central1-docker.pkg.dev/bitly-tidepool-dev/tidepool-managed/hello-world:${{ github.sha }} \
            --region=us-central1 \
            --project=bitly-tidepool-dev \
            --quiet

